/*
 * SelerShopView.java
 */

package selershop;

import java.awt.Color;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import selershop.Plotno;

/**
 * The application's main frame.
 */
public class SelerShopView extends FrameView {
    
    public SelerShopView(SingleFrameApplication app) {
        super(app);

        initComponents();
        //HistogramKanal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wszystkie", "Czerwony", "Zielony", "Niebieski" }));
        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        /*if (aboutBox == null) {
            JFrame mainFrame = SelerShopApp.getApplication().getMainFrame();
            aboutBox = new SelerShopAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SelerShopApp.getApplication().show(aboutBox);*/
    }

    
    public boolean pobierzWartosc() {
        String wartosc_str = JOptionPane.showInputDialog(null, "Wpisz wartość : ", "SelerShop - Wpisz wartość", 1);
        try { wartosc = new Float(wartosc_str);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Pomyśl zanim wpiszesz! " + wartosc_str + " to nie liczba.", "SelerShop", 1);
        }
        if(wartosc_str != null) {
            // pobrano
            return true;
        }
        else {
            // niepobrano
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        plotno = new selershop.Plotno();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelnahistogramy = new javax.swing.JPanel();
        histogramPanel = new myprzegladarka.histogramPanel();
        histogramPanelR = new myprzegladarka.histogramPanel();
        histogramPanelG = new myprzegladarka.histogramPanel();
        histogramPanelB = new myprzegladarka.histogramPanel();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        otworz = new javax.swing.JMenuItem();
        zapisz = new javax.swing.JMenuItem();
        resetuj = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        dodawanie = new javax.swing.JMenuItem();
        mnozenie = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        usredniajacy = new javax.swing.JMenuItem();
        lp2 = new javax.swing.JMenuItem();
        gauss = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        gorny1 = new javax.swing.JMenuItem();
        gorny2 = new javax.swing.JMenuItem();
        gorny3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        krawedziePoziomy = new javax.swing.JMenuItem();
        krawedziePionowy = new javax.swing.JMenuItem();
        laplacian = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        stiffness = new javax.swing.JMenuItem();
        wlasny = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        wyrownanie = new javax.swing.JMenuItem();
        binaryzacja = new javax.swing.JMenuItem();
        obliczHistogram = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        jScrollPane.setName("jScrollPane"); // NOI18N

        plotno.setName("plotno"); // NOI18N

        javax.swing.GroupLayout plotnoLayout = new javax.swing.GroupLayout(plotno);
        plotno.setLayout(plotnoLayout);
        plotnoLayout.setHorizontalGroup(
            plotnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        plotnoLayout.setVerticalGroup(
            plotnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(plotno);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelnahistogramy.setName("panelnahistogramy"); // NOI18N

        histogramPanel.setName("histogramPanel"); // NOI18N

        javax.swing.GroupLayout histogramPanelLayout = new javax.swing.GroupLayout(histogramPanel);
        histogramPanel.setLayout(histogramPanelLayout);
        histogramPanelLayout.setHorizontalGroup(
            histogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        histogramPanelLayout.setVerticalGroup(
            histogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        histogramPanelR.setName("histogramPanelR"); // NOI18N

        javax.swing.GroupLayout histogramPanelRLayout = new javax.swing.GroupLayout(histogramPanelR);
        histogramPanelR.setLayout(histogramPanelRLayout);
        histogramPanelRLayout.setHorizontalGroup(
            histogramPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        histogramPanelRLayout.setVerticalGroup(
            histogramPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        histogramPanelG.setName("histogramPanelG"); // NOI18N

        javax.swing.GroupLayout histogramPanelGLayout = new javax.swing.GroupLayout(histogramPanelG);
        histogramPanelG.setLayout(histogramPanelGLayout);
        histogramPanelGLayout.setHorizontalGroup(
            histogramPanelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        histogramPanelGLayout.setVerticalGroup(
            histogramPanelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        histogramPanelB.setName("histogramPanelB"); // NOI18N

        javax.swing.GroupLayout histogramPanelBLayout = new javax.swing.GroupLayout(histogramPanelB);
        histogramPanelB.setLayout(histogramPanelBLayout);
        histogramPanelBLayout.setHorizontalGroup(
            histogramPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        histogramPanelBLayout.setVerticalGroup(
            histogramPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelnahistogramyLayout = new javax.swing.GroupLayout(panelnahistogramy);
        panelnahistogramy.setLayout(panelnahistogramyLayout);
        panelnahistogramyLayout.setHorizontalGroup(
            panelnahistogramyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnahistogramyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelnahistogramyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnahistogramyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(histogramPanelR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(histogramPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(histogramPanelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(histogramPanelG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelnahistogramyLayout.setVerticalGroup(
            panelnahistogramyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnahistogramyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(histogramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(histogramPanelR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(histogramPanelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(histogramPanelG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(selershop.SelerShopApp.class).getContext().getResourceMap(SelerShopView.class);
        jTabbedPane1.addTab(resourceMap.getString("panelnahistogramy.TabConstraints.tabTitle"), panelnahistogramy); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        otworz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        otworz.setText(resourceMap.getString("otworz.text")); // NOI18N
        otworz.setName("otworz"); // NOI18N
        otworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otworzActionPerformed(evt);
            }
        });
        fileMenu.add(otworz);

        zapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        zapisz.setText(resourceMap.getString("zapisz.text")); // NOI18N
        zapisz.setName("zapisz"); // NOI18N
        zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszActionPerformed(evt);
            }
        });
        fileMenu.add(zapisz);

        resetuj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        resetuj.setText(resourceMap.getString("resetuj.text")); // NOI18N
        resetuj.setName("resetuj"); // NOI18N
        resetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetujActionPerformed(evt);
            }
        });
        fileMenu.add(resetuj);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(selershop.SelerShopApp.class).getContext().getActionMap(SelerShopView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        dodawanie.setText(resourceMap.getString("dodawanie.text")); // NOI18N
        dodawanie.setName("dodawanie"); // NOI18N
        dodawanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodawanieActionPerformed(evt);
            }
        });
        jMenu1.add(dodawanie);

        mnozenie.setText(resourceMap.getString("mnozenie.text")); // NOI18N
        mnozenie.setName("mnozenie"); // NOI18N
        mnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnozenieActionPerformed(evt);
            }
        });
        jMenu1.add(mnozenie);

        menuBar.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        usredniajacy.setText(resourceMap.getString("usredniajacy.text")); // NOI18N
        usredniajacy.setName("usredniajacy"); // NOI18N
        usredniajacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usredniajacyActionPerformed(evt);
            }
        });
        jMenu2.add(usredniajacy);

        lp2.setText(resourceMap.getString("lp2.text")); // NOI18N
        lp2.setName("lp2"); // NOI18N
        lp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lp2ActionPerformed(evt);
            }
        });
        jMenu2.add(lp2);

        gauss.setText(resourceMap.getString("gauss.text")); // NOI18N
        gauss.setName("gauss"); // NOI18N
        gauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaussActionPerformed(evt);
            }
        });
        jMenu2.add(gauss);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMenu2.add(jSeparator1);

        gorny1.setText(resourceMap.getString("gorny1.text")); // NOI18N
        gorny1.setName("gorny1"); // NOI18N
        gorny1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorny1ActionPerformed(evt);
            }
        });
        jMenu2.add(gorny1);

        gorny2.setText(resourceMap.getString("gorny2.text")); // NOI18N
        gorny2.setName("gorny2"); // NOI18N
        gorny2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorny2ActionPerformed(evt);
            }
        });
        jMenu2.add(gorny2);

        gorny3.setText(resourceMap.getString("gorny3.text")); // NOI18N
        gorny3.setName("gorny3"); // NOI18N
        gorny3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorny3ActionPerformed(evt);
            }
        });
        jMenu2.add(gorny3);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu2.add(jSeparator2);

        krawedziePoziomy.setText(resourceMap.getString("krawedziePoziomy.text")); // NOI18N
        krawedziePoziomy.setName("krawedziePoziomy"); // NOI18N
        krawedziePoziomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krawedziePoziomyActionPerformed(evt);
            }
        });
        jMenu2.add(krawedziePoziomy);

        krawedziePionowy.setText(resourceMap.getString("krawedziePionowy.text")); // NOI18N
        krawedziePionowy.setName("krawedziePionowy"); // NOI18N
        krawedziePionowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krawedziePionowyActionPerformed(evt);
            }
        });
        jMenu2.add(krawedziePionowy);

        laplacian.setText(resourceMap.getString("laplacian.text")); // NOI18N
        laplacian.setName("laplacian"); // NOI18N
        laplacian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laplacianActionPerformed(evt);
            }
        });
        jMenu2.add(laplacian);

        jSeparator3.setName("jSeparator3"); // NOI18N
        jMenu2.add(jSeparator3);

        stiffness.setText(resourceMap.getString("stiffness.text")); // NOI18N
        stiffness.setName("stiffness"); // NOI18N
        stiffness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiffnessActionPerformed(evt);
            }
        });
        jMenu2.add(stiffness);

        wlasny.setText(resourceMap.getString("wlasny.text")); // NOI18N
        wlasny.setName("wlasny"); // NOI18N
        wlasny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wlasnyActionPerformed(evt);
            }
        });
        jMenu2.add(wlasny);

        menuBar.add(jMenu2);

        jMenu3.setText(resourceMap.getString("jMenu3.text")); // NOI18N
        jMenu3.setName("jMenu3"); // NOI18N

        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text")); // NOI18N
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text")); // NOI18N
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenu3.add(jMenuItem6);

        menuBar.add(jMenu3);

        jMenu4.setText(resourceMap.getString("jMenu4.text")); // NOI18N
        jMenu4.setName("jMenu4"); // NOI18N

        wyrownanie.setText(resourceMap.getString("wyrownanie.text")); // NOI18N
        wyrownanie.setName("wyrownanie"); // NOI18N
        wyrownanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyrownanieActionPerformed(evt);
            }
        });
        jMenu4.add(wyrownanie);

        binaryzacja.setText(resourceMap.getString("binaryzacja.text")); // NOI18N
        binaryzacja.setName("binaryzacja"); // NOI18N
        binaryzacja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryzacjaActionPerformed(evt);
            }
        });
        jMenu4.add(binaryzacja);

        obliczHistogram.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        obliczHistogram.setText(resourceMap.getString("obliczHistogram.text")); // NOI18N
        obliczHistogram.setName("obliczHistogram"); // NOI18N
        obliczHistogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obliczHistogramActionPerformed(evt);
            }
        });
        jMenu4.add(obliczHistogram);

        menuBar.add(jMenu4);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void otworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otworzActionPerformed
        try {
            plotno.Otworz();
        } catch (IOException ex) {
            Logger.getLogger(SelerShopView.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_otworzActionPerformed

    private void resetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetujActionPerformed
        try {        
            plotno.Resetuj();
        } catch (IOException ex) {
            Logger.getLogger(SelerShopView.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_resetujActionPerformed

    private void zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszActionPerformed
        try {        
            plotno.Zapisz();
        } catch (IOException ex) {
            Logger.getLogger(SelerShopView.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_zapiszActionPerformed

    private void dodawanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodawanieActionPerformed
        if(this.pobierzWartosc()){
            Float a = new Float(1);
            plotno.Punkt(a, wartosc);
        }
        //JOptionPane.showMessageDialog(null, wartosc, "SelerShop", 1);
    }//GEN-LAST:event_dodawanieActionPerformed

    private void mnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnozenieActionPerformed
        if(this.pobierzWartosc()){
            Float a = new Float(0);
            plotno.Punkt(wartosc, a);
        }
    }//GEN-LAST:event_mnozenieActionPerformed

    private void gaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaussActionPerformed
        // http://en.wikipedia.org/wiki/Gaussian_blur#Sample_Gaussian_matrix
        float[] matrix = {
            0.00000067f, 0.00002292f, 0.00019117f, 0.00038771f, 0.00019117f, 0.00002292f, 0.00000067f,
            0.00002292f, 0.00078633f, 0.00655965f, 0.01330373f, 0.00655965f, 0.00078633f, 0.00002292f,
            0.00019117f, 0.00655965f, 0.05472157f, 0.11098164f, 0.05472157f, 0.00655965f, 0.00019117f,
            0.00038771f, 0.01330373f, 0.11098164f, 0.22508352f, 0.11098164f, 0.01330373f, 0.00038771f,
            0.00019117f, 0.00655965f, 0.05472157f, 0.11098164f, 0.05472157f, 0.00655965f, 0.00019117f,
            0.00002292f, 0.00078633f, 0.00655965f, 0.01330373f, 0.00655965f, 0.00078633f, 0.00002292f,
            0.00000067f, 0.00002292f, 0.00019117f, 0.00038771f, 0.00019117f, 0.00002292f, 0.00000067f
        };
        int rozmiar = 7;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_gaussActionPerformed

    private void laplacianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laplacianActionPerformed
        // http://en.wikipedia.org/wiki/Laplacian_matrix
        float[] matrix = {
            2f, -1f, 0f, 0f, -1f, 0f,
            -1f, 3f, -1f, 0f, -1f, 0f,
            0f, -1f, 2f, -1f, 0f, 0f, 
            0f, 0f, -1f, 3f, -1f, -1f, 
            -1f, -1f, 0f, -1f, 3f, 0f, 
            0f, 0f, 0f, -1f, 0f, 1f
        };
        int rozmiar = 6;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_laplacianActionPerformed

    private void usredniajacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usredniajacyActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            1/9f,1/9f,1/9f,
            1/9f,1/9f,1/9f,
            1/9f,1/9f,1/9f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_usredniajacyActionPerformed

    private void lp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lp2ActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            1/16f,1/16f,1/16f,
            1/16f,4/16f,1/16f,
            1/16f,1/16f,1/16f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_lp2ActionPerformed

    private void gorny1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorny1ActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            -1f,-1f,-1f,
            -1f,9f,-1f,
            -1f,-1f,-1f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_gorny1ActionPerformed

    private void gorny2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorny2ActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            1f,-2f,1f,
            -2f,5f,-2f,
            1f,-2f,1f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_gorny2ActionPerformed

    private void gorny3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorny3ActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            0f,-1/16f,0f,
            -1/16f,20/16f,-1/16f,
            0f,-1/16f,0f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_gorny3ActionPerformed

    private void krawedziePoziomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krawedziePoziomyActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            0f,-1f,0f,
            0f,1f,0f,
            0f,0f,0f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_krawedziePoziomyActionPerformed

    private void krawedziePionowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krawedziePionowyActionPerformed
        // http://www.projektydoszkoly.za.pl/index.html#dolno
        float[] matrix = {
            0f,0f,0f,
            -1f,1f,0f,
            0f,0f,0f
        };
        int rozmiar = 3;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_krawedziePionowyActionPerformed

    private void stiffnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiffnessActionPerformed
        // http://en.wikipedia.org/wiki/Stiffness_matrix
        float[] matrix = {
            13f,-1f, 0f, 0f, -12f, 0f, 
            -1f, 3f, -1f, 0f, -1f, 0f, 
            0f, -1f, 2f, -1f, 0f, 0f, 
            0f, 0f, -1f, 3f, -1f, -1f, 
            -12f, -1f, 0f, -1f, 14f, 0f, 
            0f, 0f, 0f, -1f, 0f, 1f
        };
        int rozmiar = 6;
        plotno.Splot(matrix, rozmiar);
    }//GEN-LAST:event_stiffnessActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed
    private void wlasnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wlasnyActionPerformed

    }//GEN-LAST:event_wlasnyActionPerformed

    private void obliczHistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obliczHistogramActionPerformed
        plotno.ObliczHistogram();
        histogramPanel.DrawHistogram(plotno.histogram, Color.black);
        histogramPanelR.DrawHistogram(plotno.histogramR, Color.red);
        histogramPanelG.DrawHistogram(plotno.histogramG, Color.green);
        histogramPanelB.DrawHistogram(plotno.histogramB, Color.blue);
    }//GEN-LAST:event_obliczHistogramActionPerformed

    private void wyrownanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyrownanieActionPerformed
        plotno.wyrownanie();
    }//GEN-LAST:event_wyrownanieActionPerformed

    private void binaryzacjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryzacjaActionPerformed
        if(this.pobierzWartosc()){
            Float a = new Float(0);
            plotno.Binaryzacja(wartosc);
        }
    }//GEN-LAST:event_binaryzacjaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem binaryzacja;
    private javax.swing.JMenuItem dodawanie;
    private javax.swing.JMenuItem gauss;
    private javax.swing.JMenuItem gorny1;
    private javax.swing.JMenuItem gorny2;
    private javax.swing.JMenuItem gorny3;
    private myprzegladarka.histogramPanel histogramPanel;
    private myprzegladarka.histogramPanel histogramPanelB;
    private myprzegladarka.histogramPanel histogramPanelG;
    private myprzegladarka.histogramPanel histogramPanelR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem krawedziePionowy;
    private javax.swing.JMenuItem krawedziePoziomy;
    private javax.swing.JMenuItem laplacian;
    private javax.swing.JMenuItem lp2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnozenie;
    private javax.swing.JMenuItem obliczHistogram;
    private javax.swing.JMenuItem otworz;
    private javax.swing.JPanel panelnahistogramy;
    private selershop.Plotno plotno;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JMenuItem resetuj;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenuItem stiffness;
    private javax.swing.JMenuItem usredniajacy;
    private javax.swing.JMenuItem wlasny;
    private javax.swing.JMenuItem wyrownanie;
    private javax.swing.JMenuItem zapisz;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
    private Float wartosc;
}
